#!/bin/bash

cd lib
make $1 $2 || exit

cd usb
make $1 $2 || exit
cd ..

cd input
make $1 $2 || exit
cd ..

cd fs
make $1 $2 || exit

cd fat
make $1 $2 || exit
cd ..

cd ..

cd sched
make $1 $2 || exit
cd ..

cd net
make $1 $2 || exit
cd ..

cd bt
make $1 $2 || exit
cd ..

cd ..

cd kernel
make $1 $2 || exit
cd ..

rm kernel8.img
mv kernel/kernel8.img kernel8.img

cd ..

